Implementation/collection service
Havryliuk-Vasyl/asd-java-intern pull request #17
Opened 2024-11-20 07:06 UTC by Havryliuk-Vasyl

2024-11-20 08:27 UTC, oleksandrtytkoasd commented on src/main/java/team/asd/service/CollectionService.java
> +		if (objects.length == 0) {
This condition is redundant because if objects.length == 0 then the loop at line 19 is skipped

2024-11-20 09:31 UTC, rdovgan requested changes

2024-11-20 09:31 UTC, rdovgan commented on src/main/java/team/asd/service/CollectionService.java
> +		List<Object> list = new ArrayList<>();
It's not what we expected. You just repeat the logic above. Please check the difference between unmodifiable and immutable lists.

2024-11-20 09:31 UTC, rdovgan commented on src/main/java/team/asd/service/CollectionService.java
> +		for (Object object : objects) {
You should not to check each object on null, just use Stream + Collector

2024-11-20 09:31 UTC, rdovgan commented on src/main/java/team/asd/service/CollectionService.java
> +		Set<Object> newSet = new HashSet<>();
Check CollectionUtils methods for the logic you do below

2024-11-26 14:36 UTC, rdovgan approved these changes

2024-11-28 09:12 UTC, merged